// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTSLx7j_1KFRzAxbeYfRkg7aUR5R3z3ik',
    appId: '1:477726614355:web:0f8b27c7ee4fec4216b7a6',
    messagingSenderId: '477726614355',
    projectId: 'task-manager-daa8f',
    authDomain: 'task-manager-daa8f.firebaseapp.com',
    storageBucket: 'task-manager-daa8f.firebasestorage.app',
    measurementId: 'G-XT8WDH50PT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg4gNI2bLmwhYWB_zcbZhR6_AWWUtCqPA',
    appId: '1:477726614355:android:77ad19a4a280555b16b7a6',
    messagingSenderId: '477726614355',
    projectId: 'task-manager-daa8f',
    storageBucket: 'task-manager-daa8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGqViua9WDN3Ad-KykJ2RKohL4MwI60co',
    appId: '1:477726614355:ios:05351fc66943d55916b7a6',
    messagingSenderId: '477726614355',
    projectId: 'task-manager-daa8f',
    storageBucket: 'task-manager-daa8f.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGqViua9WDN3Ad-KykJ2RKohL4MwI60co',
    appId: '1:477726614355:ios:05351fc66943d55916b7a6',
    messagingSenderId: '477726614355',
    projectId: 'task-manager-daa8f',
    storageBucket: 'task-manager-daa8f.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTSLx7j_1KFRzAxbeYfRkg7aUR5R3z3ik',
    appId: '1:477726614355:web:d79cbb178f6961d916b7a6',
    messagingSenderId: '477726614355',
    projectId: 'task-manager-daa8f',
    authDomain: 'task-manager-daa8f.firebaseapp.com',
    storageBucket: 'task-manager-daa8f.firebasestorage.app',
    measurementId: 'G-NYZBT142TN',
  );
}
